# Generated by Django 4.2.10 on 2024-04-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="address",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
