# Generated by Django 4.2.11 on 2024-04-23 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "app",
            "0003_student_code_student_school_alter_document_file_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="forum",
            name="description",
            field=models.TextField(blank=True, default="", max_length=2048),
        ),
        migrations.AlterField(
            model_name="forum",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
