# Generated by Django 4.2.11 on 2024-04-27 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_forum_description_alter_forum_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="attachments",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="post_attachments",
                to="app.attachment",
            ),
        ),
    ]
