# Generated by Django 4.2.11 on 2024-04-27 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_post_attachments"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "title",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "content",
                    models.TextField(blank=True, default="", max_length=5000),
                ),
                (
                    "attachments",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="post_attachments",
                        to="app.attachment",
                    ),
                ),
                (
                    "forum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_forums",
                        to="app.forum",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_students",
                        to="app.student",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="post_tags", to="app.tag"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="Post",
        ),
    ]
