# Generated by Django 4.2.11 on 2024-04-27 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_article_delete_post"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="document",
            name="subjects",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="subject_documents",
                to="app.subject",
            ),
        ),
    ]
