# Generated by Django 4.2.11 on 2024-05-04 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_subject_document_subjects"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="attachments",
            field=models.ManyToManyField(
                blank=True,
                related_name="post_attachments",
                to="app.attachment",
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="subjects",
            field=models.ManyToManyField(
                blank=True, related_name="subject_documents", to="app.subject"
            ),
        ),
    ]
