# Generated by Django 4.2.11 on 2024-05-04 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_alter_article_attachments_alter_document_subjects"),
    ]

    operations = [
        migrations.CreateModel(
            name="Connect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "description",
                    models.TextField(blank=True, default="", max_length=2048),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owner_connects",
                        to="app.student",
                    ),
                ),
                (
                    "people",
                    models.ManyToManyField(
                        blank=True,
                        related_name="people_connects",
                        to="app.student",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_connects",
                        to="app.subject",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
