# Generated by Django 4.2.11 on 2024-05-04 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_connect"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConnectTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "description",
                    models.TextField(blank=True, default="", max_length=1000),
                ),
                ("accepted", models.BooleanField(default=False)),
                (
                    "connect",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connect_tickets",
                        to="app.connect",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_connect_tickets",
                        to="app.student",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
