# Generated by Django 4.2.11 on 2024-05-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_connectticket"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="connectticket",
            name="description",
        ),
        migrations.AddField(
            model_name="connectticket",
            name="message",
            field=models.TextField(blank=True, default="", max_length=1000),
        ),
    ]
