# Generated by Django 4.2.11 on 2024-05-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_remove_connectticket_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="connect",
            name="people",
        ),
        migrations.AddField(
            model_name="connect",
            name="max_people",
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
