# Generated by Django 4.2.4 on 2024-05-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_remove_connect_people_connect_max_people"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="selected",
            field=models.BooleanField(default=False),
        ),
    ]
