# Generated by Django 4.2.4 on 2024-05-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_extracurricularactivity_category_selected"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="selected",
            field=models.BooleanField(default=False),
        ),
    ]
