# Generated by Django 4.2.4 on 2024-05-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_tag_selected"),
    ]

    operations = [
        migrations.CreateModel(
            name="Slider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                ("url", models.URLField()),
                ("image", models.FileField(upload_to="sliderIMG/")),
            ],
        ),
    ]
