# Generated by Django 4.2.10 on 2024-05-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_slider"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailRegister",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=255)),
            ],
        ),
    ]
