# Generated by Django 4.2.11 on 2024-05-07 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("app", "0017_emailregister"),
    ]

    operations = [
        migrations.AlterField(
            model_name="like",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="content_likes",
                to="contenttypes.contenttype",
            ),
        ),
    ]
