# Generated by Django 5.2 on 2025-04-17 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0021_dynamicquestion_fixedquestion_answer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answer",
            name="dynamic_question",
        ),
        migrations.RemoveField(
            model_name="answer",
            name="fixed_question",
        ),
        migrations.RemoveField(
            model_name="answer",
            name="user",
        ),
        migrations.DeleteModel(
            name="DynamicQuestion",
        ),
        migrations.DeleteModel(
            name="FixedQuestion",
        ),
        migrations.DeleteModel(
            name="Answer",
        ),
    ]
