# Generated by Django 4.2.20 on 2025-04-19 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0024_chatroom_alter_message_room_delete_room"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatroom",
            name="connect",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="chat_room",
                serialize=False,
                to="app.connect",
            ),
        ),
    ]
